/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EntryInput = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'amountRs' : IDL.Nat,
  'manualDate' : IDL.Text,
});
export const CreateEntryError = IDL.Variant({
  'emptyField' : IDL.Record({ 'field' : IDL.Text, 'message' : IDL.Text }),
  'invalidAmount' : IDL.Record({ 'message' : IDL.Text }),
});
export const DeleteEntryError = IDL.Variant({
  'notFound' : IDL.Record({ 'message' : IDL.Text }),
  'unauthorized' : IDL.Record({ 'message' : IDL.Text }),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Entry = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'owner' : IDL.Opt(IDL.Principal),
  'createdAt' : Time,
  'mobileNumber' : IDL.Text,
  'amountRs' : IDL.Nat,
  'manualDate' : IDL.Text,
});
export const UpdateEntryError = IDL.Variant({
  'emptyField' : IDL.Record({ 'field' : IDL.Text, 'message' : IDL.Text }),
  'notFound' : IDL.Record({ 'message' : IDL.Text }),
  'unauthorized' : IDL.Record({ 'message' : IDL.Text }),
  'invalidAmount' : IDL.Record({ 'message' : IDL.Text }),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEntry' : IDL.Func([EntryInput], [IDL.Opt(CreateEntryError)], []),
  'deleteEntry' : IDL.Func([IDL.Text], [IDL.Opt(DeleteEntryError)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listEntriesNewestFirst' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEntry' : IDL.Func(
      [IDL.Text, EntryInput],
      [IDL.Opt(UpdateEntryError)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EntryInput = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'amountRs' : IDL.Nat,
    'manualDate' : IDL.Text,
  });
  const CreateEntryError = IDL.Variant({
    'emptyField' : IDL.Record({ 'field' : IDL.Text, 'message' : IDL.Text }),
    'invalidAmount' : IDL.Record({ 'message' : IDL.Text }),
  });
  const DeleteEntryError = IDL.Variant({
    'notFound' : IDL.Record({ 'message' : IDL.Text }),
    'unauthorized' : IDL.Record({ 'message' : IDL.Text }),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Entry = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'owner' : IDL.Opt(IDL.Principal),
    'createdAt' : Time,
    'mobileNumber' : IDL.Text,
    'amountRs' : IDL.Nat,
    'manualDate' : IDL.Text,
  });
  const UpdateEntryError = IDL.Variant({
    'emptyField' : IDL.Record({ 'field' : IDL.Text, 'message' : IDL.Text }),
    'notFound' : IDL.Record({ 'message' : IDL.Text }),
    'unauthorized' : IDL.Record({ 'message' : IDL.Text }),
    'invalidAmount' : IDL.Record({ 'message' : IDL.Text }),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEntry' : IDL.Func([EntryInput], [IDL.Opt(CreateEntryError)], []),
    'deleteEntry' : IDL.Func([IDL.Text], [IDL.Opt(DeleteEntryError)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listEntriesNewestFirst' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEntry' : IDL.Func(
        [IDL.Text, EntryInput],
        [IDL.Opt(UpdateEntryError)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };