/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CreateEntryError = {
    'emptyField' : { 'field' : string, 'message' : string }
  } |
  { 'invalidAmount' : { 'message' : string } };
export type DeleteEntryError = { 'notFound' : { 'message' : string } } |
  { 'unauthorized' : { 'message' : string } };
export interface Entry {
  'id' : string,
  'customerName' : string,
  'owner' : [] | [Principal],
  'createdAt' : Time,
  'mobileNumber' : string,
  'amountRs' : bigint,
  'manualDate' : string,
}
export interface EntryInput {
  'id' : string,
  'customerName' : string,
  'mobileNumber' : string,
  'amountRs' : bigint,
  'manualDate' : string,
}
export type Time = bigint;
export type UpdateEntryError = {
    'emptyField' : { 'field' : string, 'message' : string }
  } |
  { 'notFound' : { 'message' : string } } |
  { 'unauthorized' : { 'message' : string } } |
  { 'invalidAmount' : { 'message' : string } };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEntry' : ActorMethod<[EntryInput], [] | [CreateEntryError]>,
  'deleteEntry' : ActorMethod<[string], [] | [DeleteEntryError]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listEntriesNewestFirst' : ActorMethod<[], Array<Entry>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEntry' : ActorMethod<[string, EntryInput], [] | [UpdateEntryError]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];